#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm test

FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.json" "*.scss"  "*.css" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --write --print-width 120

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
