---
name: Create release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      ref:
        description: The tag to checkout.
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Remove 'v' prefix from tag
        id: tag-without-v-prefix
        run: echo "value=$(echo ${{ github.event.inputs.ref || github.ref_name }} | tr -d v)" >> $GITHUB_OUTPUT

      - name: Generate release ext.json file
        uses: marc-sensenich/sn-extension-description-action@v1
        with:
          identifier: com.marc-sensenich.sn-nord-theme
          name: Nord
          description: An arctic, north-bluish clean and elegant Standard Notes theme.
          content_type: SN|Theme
          area: themes
          version: ${{ steps.tag-without-v-prefix.outputs.value }}
          url: https://cdn.jsdelivr.net/gh/marc-sensenich/sn-nord-theme@${{ github.event.inputs.ref || github.ref_name }}/dist/dist.css
          download_url: https://github.com/marc-sensenich/sn-nord-theme/archive/refs/tags/${{ github.event.inputs.ref || github.ref_name }}.zip
          latest_url: https://marc-sensenich.github.io/sn-nord-theme/ext.json
          marketing_url: https://github.com/marc-sensenich/sn-nord-theme#readme
          dock_icon_background_color: '#88C0D0'
          dock_icon_foreground_color: '#88C0D0'
          dock_icon_border_color: '#88C0D0'
          output_path: ext.json

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.ref || github.ref_name }}
          files: ext.json
          draft: false
          prerelease: false
          generate_release_notes: true

